### ISSUE TITLE
Suggestion: Darken color of the explorer

### ISSUE THREAD

**Issue by Zaczero** [ozkanonur/vscode-deepdark-material#1]
First of all awesome theme!! Fell in love with it immediately.
However I got a small suggestion for you.
I think you should darken the color of the explorer.

### Before:
![](https://i.imgur.com/cg6P6HY.png)

### After:
![](https://i.imgur.com/9tHFdTm.png)

I've used `#0b0b0b` but it's up to you 🦊
Just don't use same color as for the editor otherwise it will blend together.

**Comment by ozkanonur** [comment]
Thanks for giving some ideas about the theme, I think I could make it a bit darker but what you did is makes theme looks like totally black. Grey + Black looks really good but this is just opinion and it comes different by person to another person. At this point I think I will add 1 more alternative theme 'Full Black Deepdark' which will come installed by installing this theme. So after who installs the theme he will get 2 options. First option will be 'Default Deepdark' other option will be 'Full Black Deepdark'. I hope this idea will make you feel better and again thanks for feedback appreciative that. :+1:

**Comment by ozkanonur** [comment]
Thanks for giving some ideas about the theme, I think I could make it a bit darker but what you did is makes theme looks like totally black. Grey + Black looks really good but this is just opinion and it comes different by person to another person. At this point I think I will add 1 more alternative theme 'Full Black Deepdark' which will come installed by installing this theme. So after who installs the theme he will get 2 options. First option will be 'Default Deepdark' other option will be 'Full Black Deepdark'. I hope this idea will make you feel better and again thanks for feedback appreciative that. 👍

**Comment by Zaczero** [comment]
Thanks for adding this full dark option :)
It's great now !
