### ISSUE TITLE
Sudden color changes in my files.

### ISSUE THREAD

**Issue by Pixelatex** [ozkanonur/vscode-deepdark-material#11]
When I click in a file, suddenly my text goes from white to dark green/red/orange. 

This coupled with the dark background makes everything almost unreadable. Never had this issue until the latest update of vscode. Turning off the deepdark plugin removes the color switch.

![Screenshot 2020-03-12 at 09 56 18](https://user-images.githubusercontent.com/12593377/76504300-bdeb6e00-6447-11ea-9153-a25a6899c31a.png)

**Comment by ozkanonur** [comment]
Can you tell me which os are you using ?

**Comment by MirceaConstantin** [comment]
Have the same issue on Windows 10 and macOS.

**Comment by RadoiAndrei** [comment]
Same on Windows 10, happened after the newest VS Code update. It only seems to affect variable names and keys in javascript.

**Comment by ozkanonur** [comment]
I work on it this weekend.

**Comment by ozkanonur** [comment]
The problem should be fixed with version 3.2.1.
By the way, I see a lot of themes have this issue. Probably VSCode changed something from Color references.

**Comment by xuonghuynh** [comment]
![image](https://user-images.githubusercontent.com/12775554/76730483-ea77f080-678d-11ea-9e2e-8eeffd781838.png)

I didn't like this brown color, anyway to change it to other color, thanks 😄
