### ISSUE TITLE
Open VSX Support

### ISSUE THREAD

**Issue by chaosharmonic** [ozkanonur/vscode-deepdark-material#14]
Hey there - any way you'd be willing to publish this to the Open VSX Registry? It would make this accessible to downstream projects like Theia and VSCodium, which can't access the VS Code Marketplace for licensing reasons. (In particular, various Arch Linux distros ship with Code-OSS builds by default.)

Here's a link to [some relevant documentation from the OVSX wiki](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

**Comment by Technicolor-creamsicle** [comment]
@ozkanonur I am willing to take on publishing deepdark-material to the Open VSX registry. If you don't mind making your namespace for it.

**Comment by ozkanonur** [comment]
Feel free doing it @Technicolor-creamsicle

**Comment by Technicolor-creamsicle** [comment]
Some time later today the theme will be published under my namespace from my fork of the repo, at least for now until @ozkanonur claims their namespace on Open VSX.
Currently is it published under: `technicolor-creamsicle.deepdark-material`
