### ISSUE TITLE
What font is in the screenshot·

### ISSUE THREAD

**Issue by Jianyf-Jianyf** [ozkanonur/vscode-deepdark-material#16]
![image](https://user-images.githubusercontent.com/42170635/103511665-70426500-4ea2-11eb-8af2-7ebffc1e22dc.png)

**Comment by ozkanonur** [comment]
@Jianyf-Jianyf I dont really remember, its been long time and I have changed fonts a lot. But it might be [Hack](https://sourcefoundry.org/hack)

**Comment by Jianyf-Jianyf** [comment]
> @Jianyf-Jianyf I dont really remember, its been long time and I have changed fonts a lot. But it might be [Hack](https://sourcefoundry.org/hack)

I am using Hack 😁

**Comment by ozkanonur** [comment]
@Jianyf-Jianyf check also [cascadia-code](https://github.com/microsoft/cascadia-code)
