### ISSUE TITLE
Broken update icons

### ISSUE THREAD

**Issue by Zaczero** [ozkanonur/vscode-deepdark-material#2]
I noticed a small bug whenever my VSCode or Extensions are searching for an update.
Background is only slightly darker and the only thing you see is the white circle.
There is almost no difference between back and icon.

![](https://i.imgur.com/OWjmCWg.png)

Note: Same issue happens when extensions are updating.

**Comment by ozkanonur** [comment]
<img src="https://user-images.githubusercontent.com/39852038/54820220-70627800-4caf-11e9-934e-2021b530e6f7.png"/> Fixed with update, thanks for feedback!
