### ISSUE TITLE
Suggestion: Darken color .ts file

### ISSUE THREAD

**Issue by cristobalvega96** [ozkanonur/vscode-deepdark-material#3]
Hi. first of all, your theme rocks!

But i have this little suggestion, i'm currently working with TypeScript and i'm wondering how can i prove this kind of blocks of code:

![image](https://user-images.githubusercontent.com/16980304/54943352-b2c9c600-4ef6-11e9-90fe-a74ab894ab7e.png)

When the normal theme is selected on VS Code this kind of blocks looks like this:

![image](https://user-images.githubusercontent.com/16980304/54943723-85c9e300-4ef7-11e9-99a6-331545cb32af.png)

If there is a chance to help you men just let me know, and thanks for this awesome theme!  🔥🔥🤟

**Comment by ozkanonur** [comment]
Hey man, it's nice to hear people love my themes. And yes, there are some color problems in some code types. I'll make great language support as soon as possible and it will solve your suggestion as well. Probably this weekend I can make it out. Thank you again for your nice words!

**Comment by cristobalvega96** [comment]
Great!, if i can help you in something this weekend just let me know. x)

**Comment by ozkanonur** [comment]
Color support injected to the theme with version 2.5.5. Thank you for helping me fix my bugs and add new features!

**Comment by cristobalvega96** [comment]
Wow, i just see it, you rocks!
