### ISSUE TITLE
Remove white border from the side bar.

### ISSUE THREAD

**Issue by Kvek** [ozkanonur/vscode-deepdark-material#5]
The sidebar has a white border when focused on.  Is it possible to add an option to remove the white border? I think it would look much more cleaner and in line with the rest of the theme without the border. Thanks.
(ps-One of the best themes i've ever used 👍 )

<img width="1433" alt="Screenshot 2019-04-30 at 10 07 04" src="https://user-images.githubusercontent.com/8972543/56951846-bfae8a80-6b30-11e9-8261-5e222ac47647.png">

**Comment by ozkanonur** [comment]
First of all, thank you for your feedback. That bad outline appearance has been fixed with new version 2.7.0. Just upgrade the extension then that problem will be fixed.
